### ISSUE TITLE
Please provide example for using dhcplb as a server.

### ISSUE THREAD

**Issue by bjdag1234** [facebookincubator/dhcplb#28]
Please provide an example config.json, hosts-v4.txt and/or hosts-v6.txt when dhcplb is configured as server, or at least give the public a hint on how to use this piece of wonderful open-sourced software as a dhcp server. Kindly improve documentation on the usage of dhcplb as a server.

Thank you.

**Comment by pmazzini** [comment]
I apologize for the lack of documentation.

The `hosts-v4.txt` and `hosts-v6.txt` are only used when `dhcplb` is configured as a relayer / load balancer to know where to forward packets. Internally we implement the `DHCPServerSourcer` interface and use a service discovery mechanism instead of using files.

With regards to using it as a server, I added an example of how to put everything together in [Extending DHCPLB](docs/extending-dhcplb.md). Some interfaces need to be implemented to adapt it to your infra/needs.

**Comment by pmazzini** [comment]
Let me know if it looks good or if there is something else you would like us to improve in the docs.

**Comment by pmazzini** [comment]
Closing. Reopen if needed.
